anguage: go # 声明构建语言环境
sudo: false # 开启基于容器的Travis CI任务，让编译效率更高。

notifications: # 每次构建的时候是否通知，如果不想收到通知，那就设置false吧(email: false)
  email:
    recipients:
    - hexileee@gmail.com
  on_success: change
  on_failure: always

go:
- "1.12"

install:
- go build

script:
- go test -v
